// src/components/layout.tsx
import PropTypes from "prop-types";
import React from "react";
import Footer from "./footer";
import Header from "./header";

function Layout({ children }) {
  return (
    <div className="leading-normal tracking-normal text-gray-900">
      <Header />

      <main>{children}</main>
      <Footer />
    </div>
  );
}

Layout.propTypes = {
  children: PropTypes.node.isRequired,
};

export default Layout;

// src/routes/__layout.svelte
<script lang="ts">
	import '../app.css';

	import Footer from '../components/footer.svelte';
	import Gtm from '../components/gtm.svelte';
	import Header from '../components/header.svelte';

	const gtmId = 'GTM-KCZ4PZC';
	const gtmDataPoints: string[] = [];
</script>

<Gtm {gtmId} {gtmDataPoints} />

<div class="leading-normal tracking-normal text-gray-900">
	<Header />
	<slot />
	<Footer />
</div>
