// src/routes/policies/+page.svelte
<script lang="ts">
	import ContactBanner from '../../components/contact-banner.svelte';

	const seoTitle = 'Privacy Policy and Terms of Service | Bootpack Digital';
	const seoDescription =
		'We are committed to protecting your privacy. This Privacy Policy describes how we collect and use information about you when you use our website.';
</script>

<svelte:head>
	<title>{seoTitle}</title>
	<meta name="description" content={seoDescription} />
	<meta property="og:title" content={seoTitle} />
	<meta property="og:description" content={seoDescription} />
	<meta name="twitter:title" content={seoTitle} />
	<meta name="twitter:description" content={seoDescription} />
	<script src="https://app.termageddon.com/js/termageddon.js"></script>
</svelte:head>

<div class="bg-white pb-16 pt-8">
	<div class="container mx-auto mt-16 max-w-5xl px-4 text-gray-700">
		<h1 class="text-3xl font-extrabold leading-9 tracking-tight text-navy-600 sm:leading-10">
			Privacy Policy and Terms of Service
		</h1>
		<h2 class="mt-12 text-2xl font-extrabold leading-9 text-navy-600 sm:leading-10">
			Privacy Policy
		</h2>
		<div class="prose max-w-3xl pt-4 lg:mx-24">
			<div
				id="policy"
				class="w-full max-w-3xl"
				data-policy-key="V21sb2JFbE1PRGRGZEd4TkwxRTlQUT09"
				data-extra="h-align=left&no-title=true&table-style=accordion"
			>
				Please wait while the policy is loaded. If it does not load, please
				<a
					rel="nofollow"
					href="https://app.termageddon.com/api/policy/V21sb2JFbE1PRGRGZEd4TkwxRTlQUT09?h-align=left&no-title=true&table-style=accordion"
					target="_blank">click here</a
				>
				.
			</div>
		</div>
		<h2 class="mt-12 text-2xl font-extrabold leading-9 text-navy-600 sm:leading-10">
			Terms of Service
		</h2>
		<div class="max-w-3xl pt-4 lg:mx-24">
			<h3 class="mt-8 text-2xl font-bold leading-9 text-navy-600 sm:text-2xl sm:leading-10">
				1. Terms
			</h3>
			<p class="mt-4">
				By accessing the website at{` `}
				<a class="underline" href={`/`}>https://bootpackdigital.com/</a>
				, you are agreeing to be bound by these terms of service, all applicable laws and regulations,
				and agree that you are responsible for compliance with any applicable local laws. If you do not
				agree with any of these terms, you are prohibited from using or accessing this site. The materials
				contained in this website are protected by applicable copyright and trademark law.
			</p>
			<h3 class="mt-8 text-2xl font-bold leading-9 text-navy-600 sm:text-2xl sm:leading-10">
				2. Use License
			</h3>
			<ol class="ml-8 list-roman" type="a">
				<li class="mt-2">
					Permission is granted to temporarily download one copy of the materials (information or
					software) on Bootpack Digital, LLC's website for personal, non-commercial transitory
					viewing only. This is the grant of a license, not a transfer of title, and under this
					license you may not:
					<ol class="ml-8 list-decimal" type="i">
						<li class="mt-2">modify or copy the materials;</li>
						<li class="mt-2">
							use the materials for any commercial purpose, or for any public display (commercial or
							non-commercial);
						</li>
						<li class="mt-2">
							attempt to decompile or reverse engineer any software contained on Bootpack Digital,
							LLC's website;
						</li>
						<li class="mt-2">
							remove any copyright or other proprietary notations from the materials; or
						</li>
						<li class="mt-2">
							transfer the materials to another person or "mirror" the materials on any other
							server.
						</li>
					</ol>
				</li>
				<li class="mt-2">
					This license shall automatically terminate if you violate any of these restrictions and
					may be terminated by Bootpack Digital, LLC at any time. Upon terminating your viewing of
					these materials or upon the termination of this license, you must destroy any downloaded
					materials in your possession whether in electronic or printed format.
				</li>
			</ol>
			<h3 class="mt-8 text-2xl font-bold leading-9 text-navy-600 sm:text-2xl sm:leading-10">
				3. Disclaimer
			</h3>
			<ol class="ml-8 list-roman" type="a">
				<li class="mt-2">
					The materials on Bootpack Digital, LLC's website are provided on an 'as is' basis.
					Bootpack Digital, LLC makes no warranties, expressed or implied, and hereby disclaims and
					negates all other warranties including, without limitation, implied warranties or
					conditions of merchantability, fitness for a particular purpose, or non-infringement of
					intellectual property or other violation of rights.
				</li>
				<li class="mt-2">
					Further, Bootpack Digital, LLC does not warrant or make any representations concerning the
					accuracy, likely results, or reliability of the use of the materials on its website or
					otherwise relating to such materials or on any sites linked to this site.
				</li>
			</ol>
			<h3 class="mt-8 text-2xl font-bold leading-9 text-navy-600 sm:text-2xl sm:leading-10">
				4. Limitations
			</h3>
			<p class="mt-4">
				In no event shall Bootpack Digital, LLC or its suppliers be liable for any damages
				(including, without limitation, damages for loss of data or profit, or due to business
				interruption) arising out of the use or inability to use the materials on Bootpack Digital,
				LLC's website, even if Bootpack Digital, LLC or a Bootpack Digital, LLC authorized
				representative has been notified orally or in writing of the possibility of such damage.
				Because some jurisdictions do not allow limitations on implied warranties, or limitations of
				liability for consequential or incidental damages, these limitations may not apply to you.
			</p>
			<h3 class="mt-8 text-2xl font-bold leading-9 text-navy-600 sm:text-2xl sm:leading-10">
				5. Accuracy of materials
			</h3>
			<p class="mt-4">
				The materials appearing on Bootpack Digital, LLC's website could include technical,
				typographical, or photographic errors. Bootpack Digital, LLC does not warrant that any of
				the materials on its website are accurate, complete or current. Bootpack Digital, LLC may
				make changes to the materials contained on its website at any time without notice. However
				Bootpack Digital, LLC does not make any commitment to update the materials.
			</p>
			<h3 class="mt-8 text-2xl font-bold leading-9 text-navy-600 sm:text-2xl sm:leading-10">
				6. Links
			</h3>
			<p class="mt-4">
				Bootpack Digital, LLC has not reviewed all of the sites linked to its website and is not
				responsible for the contents of any such linked site. The inclusion of any link does not
				imply endorsement by Bootpack Digital, LLC of the site. Use of any such linked website is at
				the user's own risk.
			</p>
			<h3 class="mt-8 text-2xl font-bold leading-9 text-navy-600 sm:text-2xl sm:leading-10">
				7. Modifications
			</h3>
			<p class="mt-4">
				Bootpack Digital, LLC may revise these terms of service for its website at any time without
				notice. By using this website you are agreeing to be bound by the then current version of
				these terms of service.
			</p>
			<h3 class="mt-8 text-2xl font-bold leading-9 text-navy-600 sm:text-2xl sm:leading-10">
				8. Governing Law
			</h3>
			<p class="mt-4">
				These terms and conditions are governed by and construed in accordance with the laws of UT
				and you irrevocably submit to the exclusive jurisdiction of the courts in that State or
				location.
			</p>
		</div>
	</div>
</div>

<ContactBanner textLine1="Ready to get started?" textLine2="Send us a message so we can chat." />

// src/pages/policies.tsx
import React from "react";
import Layout from "../components/layout";
import SEO from "../components/seo";
import { Link } from "gatsby";

function PrivacyPage() {
  return (
    <Layout>
      <SEO
        description="Do you have a project idea or an existing site that needs to be updated? Do you need an outside consultant? Get in touch!"
        title="Privacy Policy and Terms of Service"
      />
      <div className="bg-white pt-8 pb-16">
        <div className="container mx-auto px-4 text-gray-700 max-w-5xl mt-16">
          <h1 className="text-3xl leading-9 tracking-tight font-extrabold text-navy-600 sm:leading-10">
            Privacy Policy and Terms of Service
          </h1>
          <h2 className="mt-12 text-2xl leading-9 font-extrabold text-navy-600 sm:leading-10">
            Privacy Policy
          </h2>
          <div className="pt-4 max-w-3xl lg:mx-24">
            <p className="mt-4">
              Your privacy is important to us. It is Bootpack Digital, LLC's
              policy to respect your privacy regarding any information we may
              collect from you across our website,{` `}
              <Link className="underline" to={`/`}>
                https://bootpackdigital.com/
              </Link>
              , and other sites we own and operate.
            </p>
            <p className="mt-4">
              We only ask for personal information when we truly need it to
              provide a service to you. We collect it by fair and lawful means,
              with your knowledge and consent. We also let you know why we’re
              collecting it and how it will be used.
            </p>
            <p className="mt-4">
              We only retain collected information for as long as necessary to
              provide you with your requested service. What data we store, we’ll
              protect within commercially acceptable means to prevent loss and
              theft, as well as unauthorized access, disclosure, copying, use or
              modification.
            </p>
            <p className="mt-4">
              We don’t share any personally identifying information publicly or
              with third-parties, except when required to by law.
            </p>
            <p className="mt-4">
              Our website may link to external sites that are not operated by
              us. Please be aware that we have no control over the content and
              practices of these sites, and cannot accept responsibility or
              liability for their respective privacy policies.
            </p>
            <p className="mt-4">
              You are free to refuse our request for your personal information,
              with the understanding that we may be unable to provide you with
              some of your desired services.
            </p>
            <p className="mt-4">
              Your continued use of our website will be regarded as acceptance
              of our practices around privacy and personal information. If you
              have any questions about how we handle user data and personal
              information, feel free to{` `}
              <Link className="underline" to={`/contact`}>
                contact us
              </Link>
              .
            </p>
            <p className="mt-4">
              This policy is effective as of 1 December 2020.
            </p>
          </div>
          <h2 className="mt-12 text-2xl leading-9 font-extrabold text-navy-600 sm:leading-10">
            Terms of Service
          </h2>
          <div className="pt-4 max-w-3xl lg:mx-24">
            <h3 className="mt-8 text-2xl leading-9 font-bold text-navy-600 sm:text-2xl sm:leading-10">
              1. Terms
            </h3>
            <p className="mt-4">
              By accessing the website at{` `}
              <Link className="underline" to={`/`}>
                https://bootpackdigital.com/
              </Link>
              , you are agreeing to be bound by these terms of service, all
              applicable laws and regulations, and agree that you are
              responsible for compliance with any applicable local laws. If you
              do not agree with any of these terms, you are prohibited from
              using or accessing this site. The materials contained in this
              website are protected by applicable copyright and trademark law.
            </p>
            <h3 className="mt-8 text-2xl leading-9 font-bold text-navy-600 sm:text-2xl sm:leading-10">
              2. Use License
            </h3>
            <ol className="ml-8 list-roman" type="a">
              <li className="mt-2">
                Permission is granted to temporarily download one copy of the
                materials (information or software) on Bootpack Digital, LLC's
                website for personal, non-commercial transitory viewing only.
                This is the grant of a license, not a transfer of title, and
                under this license you may not:
                <ol className="ml-8 list-decimal" type="i">
                  <li className="mt-2">modify or copy the materials;</li>
                  <li className="mt-2">
                    use the materials for any commercial purpose, or for any
                    public display (commercial or non-commercial);
                  </li>
                  <li className="mt-2">
                    attempt to decompile or reverse engineer any software
                    contained on Bootpack Digital, LLC's website;
                  </li>
                  <li className="mt-2">
                    remove any copyright or other proprietary notations from the
                    materials; or
                  </li>
                  <li className="mt-2">
                    transfer the materials to another person or "mirror" the
                    materials on any other server.
                  </li>
                </ol>
              </li>
              <li className="mt-2">
                This license shall automatically terminate if you violate any of
                these restrictions and may be terminated by Bootpack Digital,
                LLC at any time. Upon terminating your viewing of these
                materials or upon the termination of this license, you must
                destroy any downloaded materials in your possession whether in
                electronic or printed format.
              </li>
            </ol>
            <h3 className="mt-8 text-2xl leading-9 font-bold text-navy-600 sm:text-2xl sm:leading-10">
              3. Disclaimer
            </h3>
            <ol className="ml-8 list-roman" type="a">
              <li className="mt-2">
                The materials on Bootpack Digital, LLC's website are provided on
                an 'as is' basis. Bootpack Digital, LLC makes no warranties,
                expressed or implied, and hereby disclaims and negates all other
                warranties including, without limitation, implied warranties or
                conditions of merchantability, fitness for a particular purpose,
                or non-infringement of intellectual property or other violation
                of rights.
              </li>
              <li className="mt-2">
                Further, Bootpack Digital, LLC does not warrant or make any
                representations concerning the accuracy, likely results, or
                reliability of the use of the materials on its website or
                otherwise relating to such materials or on any sites linked to
                this site.
              </li>
            </ol>
            <h3 className="mt-8 text-2xl leading-9 font-bold text-navy-600 sm:text-2xl sm:leading-10">
              4. Limitations
            </h3>
            <p className="mt-4">
              In no event shall Bootpack Digital, LLC or its suppliers be liable
              for any damages (including, without limitation, damages for loss
              of data or profit, or due to business interruption) arising out of
              the use or inability to use the materials on Bootpack Digital,
              LLC's website, even if Bootpack Digital, LLC or a Bootpack
              Digital, LLC authorized representative has been notified orally or
              in writing of the possibility of such damage. Because some
              jurisdictions do not allow limitations on implied warranties, or
              limitations of liability for consequential or incidental damages,
              these limitations may not apply to you.
            </p>
            <h3 className="mt-8 text-2xl leading-9 font-bold text-navy-600 sm:text-2xl sm:leading-10">
              5. Accuracy of materials
            </h3>
            <p className="mt-4">
              The materials appearing on Bootpack Digital, LLC's website could
              include technical, typographical, or photographic errors. Bootpack
              Digital, LLC does not warrant that any of the materials on its
              website are accurate, complete or current. Bootpack Digital, LLC
              may make changes to the materials contained on its website at any
              time without notice. However Bootpack Digital, LLC does not make
              any commitment to update the materials.
            </p>
            <h3 className="mt-8 text-2xl leading-9 font-bold text-navy-600 sm:text-2xl sm:leading-10">
              6. Links
            </h3>
            <p className="mt-4">
              Bootpack Digital, LLC has not reviewed all of the sites linked to
              its website and is not responsible for the contents of any such
              linked site. The inclusion of any link does not imply endorsement
              by Bootpack Digital, LLC of the site. Use of any such linked
              website is at the user's own risk.
            </p>
            <h3 className="mt-8 text-2xl leading-9 font-bold text-navy-600 sm:text-2xl sm:leading-10">
              7. Modifications
            </h3>
            <p className="mt-4">
              Bootpack Digital, LLC may revise these terms of service for its
              website at any time without notice. By using this website you are
              agreeing to be bound by the then current version of these terms of
              service.
            </p>
            <h3 className="mt-8 text-2xl leading-9 font-bold text-navy-600 sm:text-2xl sm:leading-10">
              8. Governing Law
            </h3>
            <p className="mt-4">
              These terms and conditions are governed by and construed in
              accordance with the laws of UT and you irrevocably submit to the
              exclusive jurisdiction of the courts in that State or location.
            </p>
          </div>
        </div>
      </div>
      <div className="bg-gray-200">
        <div className="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 lg:py-24 lg:px-8 lg:flex lg:items-center lg:justify-between">
          <h2 className="text-3xl leading-9 font-extrabold tracking-tight text-gray-900 md:text-4xl md:leading-10">
            <span className="block">Ready to get started?</span>
            <span className="block text-blue-600">
              Send us a message so we can chat.
            </span>
          </h2>
          <div className="mt-8 flex lg:flex-shrink-0 lg:mt-0">
            <div className="inline-flex rounded-md shadow">
              <Link
                className="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-blue-600 hover:bg-blue-500 transition duration-150 ease-in-out"
                to="/contact/"
              >
                Get in touch
              </Link>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default PrivacyPage;
