// src/components/contact-form.tsx
import React, { useState } from "react";
import { Formik } from "formik";
import * as Yup from "yup";

const validationSchema = Yup.object().shape({
  firstName: Yup.string()
    .min(2, `Too Short!`)
    .max(50, `Too Long!`)
    .required(`First name is Required!`),
  lastName: Yup.string()
    .min(2, `Too Short!`)
    .max(50, `Too Long!`)
    .required(`Last name is Required!`),
  email: Yup.string()
    .email(`Enter a Valid Email!`)
    .required(`Email is Required!`),
  message: Yup.string().required(`Message is Required!`),
});
const encode = (data) => {
  return Object.keys(data)
    .map((key) => encodeURIComponent(key) + `=` + encodeURIComponent(data[key]))
    .join(`&`);
};

interface ContactFields {
  firstName: string;
  lastName: string;
  email: string;
  company: string;
  phone: string;
  message: string;
}

function ContactForm() {
  const [submitted, setSubmitted] = useState(false);
  return (
    <Formik
      initialValues={
        {
          firstName: "",
          lastName: "",
          email: "",
          company: "",
          phone: "",
          message: "",
        } as ContactFields
      }
      onSubmit={(values, { setSubmitting }) => {
        fetch(`/?no-cache=1`, {
          method: `POST`,
          headers: { "Content-Type": `application/x-www-form-urlencoded` },
          body: encode({
            "form-name": `contact`,
            ...values,
          }),
        })
          .then(() => {
            setSubmitted(true);
            setSubmitting(false);
          })
          .catch((error) => {
            alert(`Error: Please Try Again!`);
            setSubmitting(false);
          });
      }}
      validationSchema={validationSchema}
    >
      {({
        values,
        errors,
        touched,
        handleChange,
        handleBlur,
        handleSubmit,
        handleReset,
        isSubmitting,
        /* and other goodies */
      }) => (
        <>
          <form
            className={submitted ? `hidden` : `visible`}
            data-netlify="true"
            data-netlify-honeypot="bot-field"
            name="contact"
            onReset={handleReset}
            onSubmit={handleSubmit}
          >
            <div className="mt-8 flex flex-wrap -mx-3 mb-6">
              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label
                  className="block tracking-wide text-gray-700 text-xs font-bold mb-2"
                  htmlFor="firstName"
                >
                  First Name*
                </label>
                <input
                  className="appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-100 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  id="firstName"
                  name="firstName"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="Jane"
                  type="text"
                />
                <p className="text-red-500 text-xs italic px-2 pt-1">
                  {errors.firstName && touched.firstName && errors.firstName}
                </p>
              </div>
              <div className="w-full md:w-1/2 px-3">
                <label
                  className="block tracking-wide text-gray-700 text-xs font-bold mb-2"
                  htmlFor="lastName"
                >
                  Last Name*
                </label>
                <input
                  className="appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-100 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  id="lastName"
                  name="lastName"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="Doe"
                  type="text"
                />
                <p className="text-red-500 text-xs italic px-2 pt-1">
                  {errors.lastName && touched.lastName && errors.lastName}
                </p>
              </div>
            </div>
            <div className="flex flex-wrap -mx-3 mb-6">
              <div className="w-full px-3 mb-0">
                <label
                  className="block tracking-wide text-gray-700 text-xs font-bold mb-2"
                  htmlFor="email"
                >
                  Email*
                </label>
                <input
                  className="appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-100 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  id="email"
                  name="email"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="jane@company.com"
                  type="email"
                />
                <p className="text-red-500 text-xs italic px-2 pt-1">
                  {errors.email && touched.email && errors.email}
                </p>
              </div>
            </div>
            <div className="flex flex-wrap -mx-3 mb-6">
              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label
                  className="block tracking-wide text-gray-700 text-xs font-bold mb-2"
                  htmlFor="company"
                >
                  Company
                </label>
                <input
                  className="appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-100 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  id="company"
                  name="company"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="Company Name"
                  type="text"
                />
                <p className="text-red-500 text-xs italic px-2 pt-1">
                  {errors.company && touched.company && errors.company}
                </p>
              </div>
              <div className="w-full md:w-1/2 px-3">
                <label
                  className="block tracking-wide text-gray-700 text-xs font-bold mb-2"
                  htmlFor="phone"
                >
                  Phone Number
                </label>
                <input
                  className="appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-100 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  id="phone"
                  name="phone"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="801-111-2222"
                  type="text"
                />
                <p className="text-red-500 text-xs italic px-2 pt-1">
                  {errors.phone && touched.phone && errors.phone}
                </p>
              </div>
            </div>
            <div className="flex flex-wrap -mx-3 mb-6">
              <div className="w-full px-3 mb-6 md:mb-0">
                <label
                  className="block tracking-wide text-gray-700 text-xs font-bold mb-2"
                  htmlFor="message"
                >
                  How Can We Help?*
                </label>
                <textarea
                  className="appearance-none block w-full bg-gray-100 text-gray-700 border border-gray-100 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                  id="message"
                  name="message"
                  onBlur={handleBlur}
                  onChange={handleChange}
                  placeholder="Please give us details about what you're trying to accomplish"
                  rows={10}
                ></textarea>
                <p className="text-red-500 text-xs italic px-2 pt-1">
                  {errors.message && touched.message && errors.message}
                </p>
              </div>
            </div>
            <button
              className="w-full lg:w-auto px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-orange-600 hover:bg-orange-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out"
              disabled={isSubmitting}
              type="submit"
            >
              Submit
            </button>
          </form>
          <div className={submitted ? `visible` : `hidden`}>
            <h2>Thank you for contacting us! We'll be in touch soon</h2>
          </div>
        </>
      )}
    </Formik>
  );
}
export default ContactForm;

// src/components/contact-form.svelte
<script lang="ts">
	let submitted = false;
	let isSubmitting = false;

	const handleSubmit = async (event: SubmitEvent) => {
		const formData = new FormData(event.target as HTMLFormElement);

		fetch('https://formspree.io/f/xgerlrdz', {
			method: 'POST',
			body: formData,
			headers: {
				Accept: 'application/json'
			}
		})
			.then((response) => {
				if (response.ok) {
					submitted = true;
					// form.reset();
				} else {
					response.json().then((data) => {
						console.error(data);
						if (Object.hasOwn(data, 'errors')) {
							errorMessage = data['errors'].map((error: any) => error['message']).join(', ');
						} else {
							errorMessage = 'Oops! There was a problem submitting your form';
						}
					});
				}
			})
			.catch((error) => {
				console.error(error);
				errorMessage = 'Oops! There was a problem submitting your form';
			});
	};

	let errors: any = {};
	let errorMessage = '';
	let touched: any = {};
</script>

<form
	class={submitted ? `hidden` : `visible`}
	name="contact"
	on:submit|preventDefault={handleSubmit}
>
	<div class="-mx-3 mt-8 mb-6 flex flex-wrap">
		<div class="mb-6 w-full px-3 md:mb-0 md:w-1/2">
			<label class="mb-2 block text-xs font-bold tracking-wide text-gray-700" for="firstName">
				First Name*
			</label>
			<input
				class="block w-full appearance-none rounded border border-gray-100 bg-gray-100 py-3 px-4 leading-tight text-gray-700 focus:border-gray-500 focus:bg-white focus:outline-none"
				id="firstName"
				name="firstName"
				placeholder="Jane"
				required
				type="text"
			/>
			<p class="px-2 pt-1 text-xs italic text-red-500">
				{#if errors.firstName && touched.firstName}
					{errors.firstName}
				{/if}
			</p>
		</div>
		<div class="w-full px-3 md:w-1/2">
			<label class="mb-2 block text-xs font-bold tracking-wide text-gray-700" for="lastName">
				Last Name*
			</label>
			<input
				class="block w-full appearance-none rounded border border-gray-100 bg-gray-100 py-3 px-4 leading-tight text-gray-700 focus:border-gray-500 focus:bg-white focus:outline-none"
				id="lastName"
				name="lastName"
				placeholder="Doe"
				required
				type="text"
			/>
			<p class="px-2 pt-1 text-xs italic text-red-500">
				{#if errors.lastName && touched.lastName}
					{errors.lastName}
				{/if}
			</p>
		</div>
	</div>
	<div class="-mx-3 mb-6 flex flex-wrap">
		<div class="mb-0 w-full px-3">
			<label class="mb-2 block text-xs font-bold tracking-wide text-gray-700" for="email">
				Email*
			</label>
			<input
				class="block w-full appearance-none rounded border border-gray-100 bg-gray-100 py-3 px-4 leading-tight text-gray-700 focus:border-gray-500 focus:bg-white focus:outline-none"
				id="email"
				name="email"
				placeholder="jane@company.com"
				required
				type="email"
			/>
			{#if errors.email && touched.email}
				{errors.email}
			{/if}
		</div>
	</div>
	<div class="-mx-3 mb-6 flex flex-wrap">
		<div class="mb-6 w-full px-3 md:mb-0 md:w-1/2">
			<label class="mb-2 block text-xs font-bold tracking-wide text-gray-700" for="company">
				Company
			</label>
			<input
				class="block w-full appearance-none rounded border border-gray-100 bg-gray-100 py-3 px-4 leading-tight text-gray-700 focus:border-gray-500 focus:bg-white focus:outline-none"
				id="company"
				name="company"
				placeholder="Company Name"
				type="text"
			/>
			{#if errors.company && touched.company}
				{errors.company}
			{/if}
		</div>
		<div class="w-full px-3 md:w-1/2">
			<label class="mb-2 block text-xs font-bold tracking-wide text-gray-700" for="phone">
				Phone Number
			</label>
			<input
				class="block w-full appearance-none rounded border border-gray-100 bg-gray-100 py-3 px-4 leading-tight text-gray-700 focus:border-gray-500 focus:bg-white focus:outline-none"
				id="phone"
				name="phone"
				placeholder="801-111-2222"
				type="text"
			/>
			{#if errors.phone && touched.phone}
				{errors.phone}
			{/if}
		</div>
	</div>
	<div class="-mx-3 mb-6 flex flex-wrap">
		<div class="mb-6 w-full px-3 md:mb-0">
			<label class="mb-2 block text-xs font-bold tracking-wide text-gray-700" for="message">
				How Can We Help?*
			</label>
			<textarea
				class="block w-full appearance-none rounded border border-gray-100 bg-gray-100 py-3 px-4 leading-tight text-gray-700 focus:border-gray-500 focus:bg-white focus:outline-none"
				id="message"
				name="message"
				placeholder="Please give us details about what you're trying to accomplish"
				required
				rows={10}
			/>
			<p class="px-2 pt-1 text-xs italic text-red-500">
				{#if errors.message && touched.message}
					{errors.message}
				{/if}
			</p>
		</div>
	</div>
	{#if errorMessage}
		<p class="px-2 pt-1 text-xs italic text-red-500">
			{errorMessage}
		</p>
	{/if}
	<button
		class="focus:shadow-outline w-full rounded-md border border-transparent bg-orange-600 px-5 py-3 text-base font-medium leading-6 text-white transition duration-150 ease-in-out hover:bg-orange-500 focus:outline-none lg:w-auto"
		disabled={isSubmitting}
		type="submit"
	>
		Submit
	</button>
</form>
<div class={submitted ? `visible` : `hidden`}>
	<h2>Thank you for contacting us! We'll be in touch soon</h2>
</div>
